# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import empty_pb2 as empty__pb2
import favorites_pb2 as favorites__pb2
import product_pb2 as product__pb2


class FavoritesStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetFavorites = channel.unary_unary(
        '/store.Favorites/GetFavorites',
        request_serializer=favorites__pb2.GetFavoritesRequest.SerializeToString,
        response_deserializer=product__pb2.ProductList.FromString,
        )
    self.UpdateFavorites = channel.unary_unary(
        '/store.Favorites/UpdateFavorites',
        request_serializer=favorites__pb2.UpdateFavoritesRequest.SerializeToString,
        response_deserializer=empty__pb2.Empty.FromString,
        )


class FavoritesServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetFavorites(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateFavorites(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FavoritesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetFavorites': grpc.unary_unary_rpc_method_handler(
          servicer.GetFavorites,
          request_deserializer=favorites__pb2.GetFavoritesRequest.FromString,
          response_serializer=product__pb2.ProductList.SerializeToString,
      ),
      'UpdateFavorites': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateFavorites,
          request_deserializer=favorites__pb2.UpdateFavoritesRequest.FromString,
          response_serializer=empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'store.Favorites', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
