# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import empty_pb2 as empty__pb2
import notifications_pb2 as notifications__pb2


class NotificationsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Notify = channel.unary_unary(
        '/store.Notifications/Notify',
        request_serializer=notifications__pb2.NotificationRequest.SerializeToString,
        response_deserializer=empty__pb2.Empty.FromString,
        )
    self.NotifyUser = channel.unary_unary(
        '/store.Notifications/NotifyUser',
        request_serializer=notifications__pb2.UserNotificationRequest.SerializeToString,
        response_deserializer=empty__pb2.Empty.FromString,
        )


class NotificationsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Notify(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NotifyUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NotificationsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Notify': grpc.unary_unary_rpc_method_handler(
          servicer.Notify,
          request_deserializer=notifications__pb2.NotificationRequest.FromString,
          response_serializer=empty__pb2.Empty.SerializeToString,
      ),
      'NotifyUser': grpc.unary_unary_rpc_method_handler(
          servicer.NotifyUser,
          request_deserializer=notifications__pb2.UserNotificationRequest.FromString,
          response_serializer=empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'store.Notifications', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
