# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notifications.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import empty_pb2 as empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='notifications.proto',
  package='store',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13notifications.proto\x12\x05store\x1a\x0b\x65mpty.proto\"C\n\x13NotificationRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\";\n\x17UserNotificationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t2\x7f\n\rNotifications\x12\x32\n\x06Notify\x12\x1a.store.NotificationRequest\x1a\x0c.store.Empty\x12:\n\nNotifyUser\x12\x1e.store.UserNotificationRequest\x1a\x0c.store.Emptyb\x06proto3')
  ,
  dependencies=[empty__pb2.DESCRIPTOR,])




_NOTIFICATIONREQUEST = _descriptor.Descriptor(
  name='NotificationRequest',
  full_name='store.NotificationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='store.NotificationRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='store.NotificationRequest.email', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='store.NotificationRequest.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=110,
)


_USERNOTIFICATIONREQUEST = _descriptor.Descriptor(
  name='UserNotificationRequest',
  full_name='store.UserNotificationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='store.UserNotificationRequest.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='store.UserNotificationRequest.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=171,
)

DESCRIPTOR.message_types_by_name['NotificationRequest'] = _NOTIFICATIONREQUEST
DESCRIPTOR.message_types_by_name['UserNotificationRequest'] = _USERNOTIFICATIONREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NotificationRequest = _reflection.GeneratedProtocolMessageType('NotificationRequest', (_message.Message,), dict(
  DESCRIPTOR = _NOTIFICATIONREQUEST,
  __module__ = 'notifications_pb2'
  # @@protoc_insertion_point(class_scope:store.NotificationRequest)
  ))
_sym_db.RegisterMessage(NotificationRequest)

UserNotificationRequest = _reflection.GeneratedProtocolMessageType('UserNotificationRequest', (_message.Message,), dict(
  DESCRIPTOR = _USERNOTIFICATIONREQUEST,
  __module__ = 'notifications_pb2'
  # @@protoc_insertion_point(class_scope:store.UserNotificationRequest)
  ))
_sym_db.RegisterMessage(UserNotificationRequest)



_NOTIFICATIONS = _descriptor.ServiceDescriptor(
  name='Notifications',
  full_name='store.Notifications',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=173,
  serialized_end=300,
  methods=[
  _descriptor.MethodDescriptor(
    name='Notify',
    full_name='store.Notifications.Notify',
    index=0,
    containing_service=None,
    input_type=_NOTIFICATIONREQUEST,
    output_type=empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='NotifyUser',
    full_name='store.Notifications.NotifyUser',
    index=1,
    containing_service=None,
    input_type=_USERNOTIFICATIONREQUEST,
    output_type=empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NOTIFICATIONS)

DESCRIPTOR.services_by_name['Notifications'] = _NOTIFICATIONS

# @@protoc_insertion_point(module_scope)
