# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import empty_pb2 as empty__pb2
import recommendations_pb2 as recommendations__pb2


class RecommendationsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RecommendUser = channel.unary_unary(
        '/store.Recommendations/RecommendUser',
        request_serializer=recommendations__pb2.RecommendUserRequest.SerializeToString,
        response_deserializer=empty__pb2.Empty.FromString,
        )


class RecommendationsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RecommendUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RecommendationsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RecommendUser': grpc.unary_unary_rpc_method_handler(
          servicer.RecommendUser,
          request_deserializer=recommendations__pb2.RecommendUserRequest.FromString,
          response_serializer=empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'store.Recommendations', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
