# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import users_pb2 as users__pb2


class UsersStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateUser = channel.unary_unary(
        '/store.Users/CreateUser',
        request_serializer=users__pb2.CreateUserRequest.SerializeToString,
        response_deserializer=users__pb2.User.FromString,
        )
    self.ReadUser = channel.unary_unary(
        '/store.Users/ReadUser',
        request_serializer=users__pb2.UserRequest.SerializeToString,
        response_deserializer=users__pb2.User.FromString,
        )
    self.UpdateUser = channel.unary_unary(
        '/store.Users/UpdateUser',
        request_serializer=users__pb2.UpdateUserRequest.SerializeToString,
        response_deserializer=users__pb2.User.FromString,
        )
    self.DeleteUser = channel.unary_unary(
        '/store.Users/DeleteUser',
        request_serializer=users__pb2.UserRequest.SerializeToString,
        response_deserializer=users__pb2.User.FromString,
        )
    self.ListUsers = channel.unary_unary(
        '/store.Users/ListUsers',
        request_serializer=users__pb2.ListUsersRequest.SerializeToString,
        response_deserializer=users__pb2.BatchUsers.FromString,
        )


class UsersServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReadUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListUsers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UsersServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateUser': grpc.unary_unary_rpc_method_handler(
          servicer.CreateUser,
          request_deserializer=users__pb2.CreateUserRequest.FromString,
          response_serializer=users__pb2.User.SerializeToString,
      ),
      'ReadUser': grpc.unary_unary_rpc_method_handler(
          servicer.ReadUser,
          request_deserializer=users__pb2.UserRequest.FromString,
          response_serializer=users__pb2.User.SerializeToString,
      ),
      'UpdateUser': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateUser,
          request_deserializer=users__pb2.UpdateUserRequest.FromString,
          response_serializer=users__pb2.User.SerializeToString,
      ),
      'DeleteUser': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteUser,
          request_deserializer=users__pb2.UserRequest.FromString,
          response_serializer=users__pb2.User.SerializeToString,
      ),
      'ListUsers': grpc.unary_unary_rpc_method_handler(
          servicer.ListUsers,
          request_deserializer=users__pb2.ListUsersRequest.FromString,
          response_serializer=users__pb2.BatchUsers.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'store.Users', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
