version: '3'

services:
  catalog_api:
    image: catalog_api
    build:
      context: catalog
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - etcd
    ports:
      - "50051:50051"
    environment:
      PORT: 50051
      MONGO_HOST: 172.28.5.1
      MONGO_PORT: 27017
      MONGO_DB: catalog
      ETCD_HOST: 172.28.4.1
      ETCD_PORT: 2379

  favorites_api:
    image: favorites_api
    build:
      context: favorites
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - etcd
    ports:
      - "50052:50051"
    environment:
      PORT: 50051
      MONGO_HOST: 172.28.5.1
      MONGO_PORT: 27017
      MONGO_DB: favorites
      ETCD_HOST: 172.28.4.1
      ETCD_PORT: 2379

  users_api:
    image: users_api
    container_name: "users_api"
    build:
      context: users
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "50053:50051"
    environment:
      PORT: 50051
      MONGO_HOST: "mongo"
      MONGO_PORT: 27017
      MONGO_DB: users

  notifications_api:
    image: notifications_api
    container_name: "notifications_api"
    build:
      context: notifications
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "50054:50051"
    environment:
      PORT: 50051

  recommendations_api:
    image: recommendations_api
    build:
      context: recommendations
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - etcd
    ports:
      - "50055:50051"
    environment:
      HOST: 172.28.7.1
      PORT: 50051
      MONGO_HOST: 172.28.5.1
      MONGO_PORT: 27017
      MONGO_DB: recommendations
      ETCD_HOST: 172.28.4.1
      ETCD_PORT: 2379

  etcd:
    image: bitnami/etcd:latest
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://172.28.4.1:2379
    ports:
      - "2379:2379"
      - "2380:2380"

  mongo:
    image: mongo:4
    container_name: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    external: true