version: '3'

services:
  catalog_api:
    image: catalog_api
    container_name: catalog_api
    build:
      context: catalog
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - 50051:50051
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: store
      MONGO_COLLECTION: products

  favorites_api:
    image: favorites_api
    container_name: favorites_api
    build:
      context: favorites
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - 50052:50051
    environment:
      GRPC_PORT: 50051
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: store
      CATALOG_GRPC_HOSTS: catalog_api;catalog_api_2
      CATALOG_GRPC_PORT: 50051
      LOAD_BALANCING_TIMEOUT: 500

  mongo:
    image: mongo:4.0
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    external:
      name: "mongo_data"