apiVersion: app/v1beta1
kind: Deployment
metadata:
  name: favorites-api
  labels:
    app: favorites-api
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: favorites-api
    spec:
      containers:
      - name: favorites-api
        image: favorites_api
        ports:
        - containerPort: 50051
        envFrom:
        - configMapRef:
            name: common-env-file
        resources: {}
      restartPolicy: Always
status: {}
