apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: users-api
  labels:
    app: users-api
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: users-api
    spec:
      containers:
      - name: users-api
        image: users_api
        imagePullPolicy: IfNotPresent # No lo pullea si lo tiene en el docker local.
        ports:
        - containerPort: 50051
        envFrom:
        - configMapRef:
            name: common-env-file # saca variables de ambiente del ConfigMap common-env-file
        resources: {}
      restartPolicy: Always
status: {}
