# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import catalog_pb2 as catalog__pb2


class CatalogStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetArticle = channel.unary_unary(
        '/Catalog/GetArticle',
        request_serializer=catalog__pb2.ArticleRequest.SerializeToString,
        response_deserializer=catalog__pb2.Article.FromString,
        )


class CatalogServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetArticle(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CatalogServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetArticle': grpc.unary_unary_rpc_method_handler(
          servicer.GetArticle,
          request_deserializer=catalog__pb2.ArticleRequest.FromString,
          response_serializer=catalog__pb2.Article.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Catalog', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
