# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: favorites.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protos.empty_pb2 as empty__pb2
import protos.product_pb2 as product__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='favorites.proto',
  package='store',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x66\x61vorites.proto\x12\x05store\x1a\x0b\x65mpty.proto\x1a\rproduct.proto\"H\n\x13GetFavoritesRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12 \n\x18with_product_description\x18\x02 \x01(\x08\"^\n\x16UpdateFavoritesRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x17\n\x0f\x61\x64\x64_product_ids\x18\x02 \x03(\t\x12\x1a\n\x12remove_product_ids\x18\x03 \x03(\t2\x8b\x01\n\tFavorites\x12>\n\x0cGetFavorites\x12\x1a.store.GetFavoritesRequest\x1a\x12.store.ProductList\x12>\n\x0fUpdateFavorites\x12\x1d.store.UpdateFavoritesRequest\x1a\x0c.store.Emptyb\x06proto3')
  ,
  dependencies=[empty__pb2.DESCRIPTOR,product__pb2.DESCRIPTOR,])




_GETFAVORITESREQUEST = _descriptor.Descriptor(
  name='GetFavoritesRequest',
  full_name='store.GetFavoritesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='store.GetFavoritesRequest.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='with_product_description', full_name='store.GetFavoritesRequest.with_product_description', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=126,
)


_UPDATEFAVORITESREQUEST = _descriptor.Descriptor(
  name='UpdateFavoritesRequest',
  full_name='store.UpdateFavoritesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='store.UpdateFavoritesRequest.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='add_product_ids', full_name='store.UpdateFavoritesRequest.add_product_ids', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remove_product_ids', full_name='store.UpdateFavoritesRequest.remove_product_ids', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=222,
)

DESCRIPTOR.message_types_by_name['GetFavoritesRequest'] = _GETFAVORITESREQUEST
DESCRIPTOR.message_types_by_name['UpdateFavoritesRequest'] = _UPDATEFAVORITESREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetFavoritesRequest = _reflection.GeneratedProtocolMessageType('GetFavoritesRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETFAVORITESREQUEST,
  __module__ = 'favorites_pb2'
  # @@protoc_insertion_point(class_scope:store.GetFavoritesRequest)
  ))
_sym_db.RegisterMessage(GetFavoritesRequest)

UpdateFavoritesRequest = _reflection.GeneratedProtocolMessageType('UpdateFavoritesRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEFAVORITESREQUEST,
  __module__ = 'favorites_pb2'
  # @@protoc_insertion_point(class_scope:store.UpdateFavoritesRequest)
  ))
_sym_db.RegisterMessage(UpdateFavoritesRequest)



_FAVORITES = _descriptor.ServiceDescriptor(
  name='Favorites',
  full_name='store.Favorites',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=225,
  serialized_end=364,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetFavorites',
    full_name='store.Favorites.GetFavorites',
    index=0,
    containing_service=None,
    input_type=_GETFAVORITESREQUEST,
    output_type=product__pb2._PRODUCTLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateFavorites',
    full_name='store.Favorites.UpdateFavorites',
    index=1,
    containing_service=None,
    input_type=_UPDATEFAVORITESREQUEST,
    output_type=empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FAVORITES)

DESCRIPTOR.services_by_name['Favorites'] = _FAVORITES

# @@protoc_insertion_point(module_scope)
