# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: healthcheck.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import empty_pb2 as empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='healthcheck.proto',
  package='store',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11healthcheck.proto\x12\x05store\x1a\x0b\x65mpty.proto22\n\x0bHealthCheck\x12#\n\x05\x43heck\x12\x0c.store.Empty\x1a\x0c.store.Emptyb\x06proto3')
  ,
  dependencies=[empty__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_HEALTHCHECK = _descriptor.ServiceDescriptor(
  name='HealthCheck',
  full_name='store.HealthCheck',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=41,
  serialized_end=91,
  methods=[
  _descriptor.MethodDescriptor(
    name='Check',
    full_name='store.HealthCheck.Check',
    index=0,
    containing_service=None,
    input_type=empty__pb2._EMPTY,
    output_type=empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HEALTHCHECK)

DESCRIPTOR.services_by_name['HealthCheck'] = _HEALTHCHECK

# @@protoc_insertion_point(module_scope)
