apiVersion: v1
kind: Service
metadata:
  name: favorites-api
spec:
  selector:
    app: favorites-api
  type: NodePort # le puse NodePort para poder acceder desde fuera del cluster. Sinó tendría que ir ClusterIP. 
  ports:
  - port: 80
    targetPort: 50051
status:
  loadBalancer: {}
