apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: users-api
  name: users-api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: users-api
    spec:
      containers:
      - env:
        - name: ETCD_HOST
          value: 172.28.4.1
        - name: ETCD_PORT
          value: "2379"
        - name: HOST
          value: 172.28.3.1
        - name: MONGO_DB
          value: users
        - name: MONGO_HOST
          value: 172.28.5.1
        - name: MONGO_PORT
          value: "27017"
        - name: PORT
          value: "50051"
        image: users_api
        name: users-api
        ports:
        - containerPort: 50051
        resources: {}
      restartPolicy: Always
status: {}
